on:
  issues:
    types: opened

name: check-package

jobs:
  check-package:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'statistical-software-review-book')
    strategy:
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
     
      - name: Trigger package check
        run: ruby ./.github/workflows/check_package.rb
        env:
          ISSUE_NUMBER: github.event.issue.number
          ISSUE_BODY: github.event.issue.body 
